panel:
  width: 1920
  height: 1080
objects:
  -
    id: "container"
    location:
      top: 0
      left: 0
    dimensions:
      width: 7740
      height: 980
  -
    id: "mickey001"
    image_url: "/img/mickey.png"
    location:
      top: 282
      left: 528
    dimensions:
      width: 162
      height: 545
    slide_in:
      top: -550
      left: 528
      duration: 1.5
  -
    id: "mickey002"
    image_url: "/img/mickey.png"
    location:
      top: 321
      left: 398
    dimensions:
      width: 162
      height: 545
    flicker:
      delay: 2.4
      min_duration: 0.1
      max_duration: 0.5
      min_opacity: 0.5
      max_opacity: 0.9
  -
    id: "mickey003"
    image_url: "/img/mickey.png"
    location:
      top: 321
      left: 659
    dimensions:
      width: 162
      height: 545
    flicker:
      delay: 2.4
      min_duration: 0.1
      max_duration: 0.5
      min_opacity: 0.5
      max_opacity: 0.9
  -
    id: "header_bio"
    image_url: "/img/header_bio.png"
    location:
      top: 301
      left: 888
    dimensions:
      width: 50
      height: 32
    slide_in:
      top: -301
      left: 888
      duration: 1.5
  -
    id: "header_bombay_to_nyc"
    image_url: "/img/header_bombay_to_nyc.png"
    location:
      top: 899
      left: 1472
    dimensions:
      width: 373
      height: 37
    slide_in:
      top: -899
      left: 1472
      duration: 2.8
  -
    id: "face_deer"
    image_url: "/img/face_deer.png"
    location:
      top: 430
      left: 1515
    dimensions:
      width: 357
      height: 262
    slide_in:
      top: 980
      left: 1515
      duration: 1.5
  -
    id: "black_structure"
    image_url: "/img/black_structure.png"
    location:
      top: -5
      left: 1872
    dimensions:
      width: 659
      height: 980
  -
    id: "yellow_cab"
    image_url: "/img/yellow_cab.png"
    location:
      top: 656
      left: 1356
    dimensions:
      width: 398
      height: 227
    slide_in:
      top: 980
      left: 1356
      duration: 1.5
  -
    id: "rickshaw_left"
    image_url: "/img/rickshaw_left.png"
    location:
      top: 671
      left: 1725
    dimensions:
      width: 264
      height: 270
    slide_in:
      top: 980
      left: 1725
      duration: 1.5
  -
    id: "luxo_lamp"
    image_url: "/img/luxo_lamp.png"
    location:
      top: 0
      left: 1052
    dimensions:
      width: 892
      height: 974
    slide_in:
      top: 980
      left: 1052
      duration: 2.2
  -
    id: "tattoo"
    image_url: "/img/tattoo.png"
    location:
      top: 97
      left: 2878
    dimensions:
      width: 877
      height: 771
  -
    id: "circle_small"
    image_url: "/img/circle_small.png"
    location:
      top: 92
      left: 3530
    dimensions:
      width: 234
      height: 234
    rotate:
      duration: 20
      degrees: 360
  -
    id: "circle_medium"
    image_url: "/img/circle_medium.png"
    location:
      top: 98
      left: 3003
    dimensions:
      width: 561
      height: 561
    rotate:
      duration: 15
      degrees: -360
  -
    id: "circle_large"
    image_url: "/img/circle_large.png"
    location:
      top: 23
      left: 2675
    dimensions:
      width: 803
      height: 803
    rotate:
      duration: 20
      degrees: 360
  -
    id: "resume_ba"
    image_url: "/img/resume_ba.png"
    alt: "BA"
    location:
      top: 45
      left: 2952
    dimensions:
      width: 242
      height: 68
    popup_banner:
      popup_content_id: "resume_ba_popup"
  -
    id: "resume_ms"
    image_url: "/img/resume_ms.png"
    alt: "MS"
    location:
      top: 177
      left: 2760
    dimensions:
      width: 238
      height: 144
    popup_banner:
      popup_content_id: "resume_ms_popup"
  -
    id: "resume_grad_assoc"
    image_url: "/img/resume_grad_assoc.png"
    alt: "Grad Associates"
    location:
      top: 874
      left: 3131
    dimensions:
      width: 188
      height: 91
    popup_banner:
      popup_content_id: "resume_grad_assoc_popup"
  -
    id: "resume_diabes"
    image_url: "/img/resume_diabes.png"
    alt: "Diabes"
    location:
      top: 675
      left: 3403
    dimensions:
      width: 189
      height: 91
    popup_banner:
      popup_content_id: "resume_diabes_popup"
  -
    id: "resume_buck_moorhead"
    image_url: "/img/resume_buck_moorhead.png"
    alt: "Buck Moorhead"
    location:
      top: 533
      left: 2702
    dimensions:
      width: 222
      height: 90
    popup_banner:
      popup_content_id: "resume_buck_moorhead_popup"
  -
    id: "resume_corgan"
    image_url: "/img/resume_corgan.png"
    alt: "Corgan"
    location:
      top: 175
      left: 3547
    dimensions:
      width: 203
      height: 121
    popup_banner:
      popup_content_id: "resume_corgan_popup"
  -
    id: "portfolio_sketch"
    image_url: "/img/portfolio_sketch.png"
    location:
      top: 72
      left: 4059
    dimensions:
      width: 1672
      height: 866
  -
    id: "city_sketch"
    image_url: "/img/city_sketch.png"
    location:
      top: 178
      left: 6175
    dimensions:
      width: 1480
      height: 628
  -
    id: "rat_animation"
    image_url: "/img/rat_animation001.png"
    location:
      top: 875
      left: 7800
    dimensions:
      width: 380
      height: 85
    sequence:
      -
        image_url: "/img/rat_animation001.png"
        duration: 0.25
      -
        image_url: "/img/rat_animation002.png"
        duration: 0.25
    from_to:
      sequence:
        -
          from:
            left: 6100
            top: 650
            scale: 0.8
          to:
            left: 7800
            top: 875
            scale: 1
          duration: 2
          min_delay: 4
          random_delay: 2
  -
    id: "elephant"
    image_url: "/img/elephant.png"
    location:
      top: 214
      left: 6117
    dimensions:
      width: 427
      height: 536
  -
    id: "header_contact"
    image_url: "/img/header_contact.png"
    location:
      top: 415
      left: 7348
    dimensions:
      width: 142
      height: 34
  -
    id: "menu_name"
    image_url: "/img/menu_name.png"
    alt: "Home"
    click_scroll:
      scroll_x: 0
      duration: 1
    location:
      top: 370
      left: 32
    dimensions:
      width: 315
      height: 41
    slide_in:
      top: -364
      left: 32
      duration: 1.5
    always_on_top:
      duration: 1
  -
    id: "menu_bio"
    image_url: "/img/menu_bio.png"
    alt: "Bio"
    click_scroll:
      scroll_x: 382
      duration: 1
    location:
      top: 417
      left: 32
    dimensions:
      width: 43
      height: 30
    slide_in:
      top: -411
      left: 32
      duration: 1.5
    always_on_top:
      duration: 1
  -
    id: "menu_gigs"
    image_url: "/img/menu_gigs.png"
    alt: "Gigs"
    click_scroll:
      scroll_x: 1875
      duration: 1
    location:
      top: 453
      left: 32
    dimensions:
      width: 59
      height: 31
    slide_in:
      top: -453
      left: 32
      duration: 1.5
    always_on_top:
      duration: 1
  -
    id: "menu_projects"
    image_url: "/img/menu_projects.png"
    alt: "Projects"
    click_scroll:
      scroll_x: 3813
      duration: 1
    location:
      top: 491
      left: 32
    dimensions:
      width: 126
      height: 31
    slide_in:
      top: -491
      left: 32
      duration: 1.5
    always_on_top:
      duration: 1
  -
    id: "menu_contact"
    image_url: "/img/menu_contact.png"
    alt: "Contact"
    click_scroll:
      scroll_x: 5748
      duration: 1
    location:
      top: 525
      left: 32
    dimensions:
      width: 112
      height: 32
    slide_in:
      top: -569
      left: 32
      duration: 1.5
    always_on_top:
      duration: 1
text:
  -
    id: "bio_text"
    copy: |
      Ligula a magna natoque condimentum ridiculus a vulputate a pretium a in parturient parturient vestibulum venenatis parturient dis consequat scelerisque a scelerisque euismod posuere dolor hendrerit cum at lectus. Odio a at venenatis adipiscing lobortis a suspendisse vestibulum consectetur libero urna ante bibendum interdum a adipiscing commodo urna dapibus a condimentum ornare bibendum dictum a sagittis parturient. Erat suspendisse gravida libero iaculis parturient ad tempus tincidunt et eget suspendisse arcu a a eget. Euismod nibh nam facilisi quis vivamus luctus aptent fusce suscipit laoreet proin velit eu interdum cubilia suspendisse commodo sapien blandit interdum a sem mauris in blandit vel a hendrerit. Sagittis ullamcorper ullamcorper mattis ut a quis a in eget a diam luctus consequat luctus magna arcu ultricies platea torquent ad donec scelerisque lacus a habitant.

      A morbi amet imperdiet natoque sem sociosqu a porttitor a ad vivamus cum a leo fames sed vestibulum a ad inceptos velit sit faucibus et curabitur senectus. Orci iaculis torquent proin a vestibulum gravida natoque per risus condimentum integer amet mus vitae. Natoque bibendum nam a a mi aenean commodo ullamcorper a integer eros parturient nascetur ullamcorper suscipit ullamcorper a praesent posuere a orci condimentum at suspendisse.

      Vel sapien gravida imperdiet elit pulvinar quam ullamcorper condimentum habitant placerat a in eros turpis elementum himenaeos adipiscing a a praesent aptent mollis et a integer. Euismod at per potenti potenti duis penatibus scelerisque suscipit primis feugiat a sagittis duis vestibulum porttitor vestibulum tempus pulvinar quis vestibulum suscipit a risus adipiscing a primis nibh neque. A a in adipiscing vivamus ullamcorper dictum dictum vestibulum accumsan ad cras hac purus adipiscing ac elit laoreet in a eleifend hac ornare blandit ridiculus. Dui ligula nam scelerisque sodales a gravida neque erat mi lacinia parturient a quis primis. Donec pharetra a hendrerit vestibulum potenti leo vehicula mattis eu sociis dapibus magnis leo scelerisque dolor elementum adipiscing volutpat sodales tincidunt parturient sem ultricies adipiscing adipiscing at cursus dolor. Parturient tellus aliquam odio condimentum purus penatibus dis rhoncus a a enim metus mus id ullamcorper magna at a mattis diam vivamus sodales quis nec magna elit.
    location:
      top: 350
      left: 888
    dimensions:
      width: 350
      height: 500
    overflow:
      y: "auto"
      x: "hidden"
    text_align: "left"
    slide_in:
      top: -520
      left: 888
      duration: 2.2
  -
    id: "contact_text"
    copy: |
      You can often find Prutha riding her zebralephant in the East village.
      But for the rest of the times find her at:
      405 E 6th street<br />
      New York, NY10009

      Email: <a href="mailto:prutharaithatha@gmail.com">prutharaithatha@gmail.com</a><br />
      BatMobile: <a href="callto:9179719271">917-971-6271</a>
    location:
      top: 450
      left: 7235
    dimensions:
      width: 350
      height: 350
    overflow:
      y: "auto"
      x: "hidden"
    text_align: "center"
popup_banner:
  -
    id: "resume_ba_popup"
    copy: |
      <div class="col-xs-12">
        <div class="pull-left col-xs-10">
          <h1>Bachelor of Architecture</h1>
          <p>University of Mumbai, India</p>
        </div>
        <div class="pull-right col-xs-2">
          <strong>May 2003</strong>
        </div>
      </div>
    screen_location:
      left: 0
      top: 50
    dimensions:
      width: 1920
      height: auto
  -
    id: "resume_ms_popup"
    copy: |
      <div class="col-xs-12">
        <div class="pull-left col-xs-10">
          <h1>Masters of Science in Sustainable Design</h1>
          <p>Carnegie Mellon University, USA</p>
        </div>
        <div class="pull-right col-xs-2">
          <strong>May 2005</strong>
        </div>
      </div>
    screen_location:
      left: 0
      top: 150
    dimensions:
      width: 1920
      height: auto
  -
    id: "resume_corgan_popup"
    copy: |
      <div class="col-xs-12">
        <div class="pull-left col-xs-10">
          <h1>Corgan Associates, Project Architect</h1>
          <p>Manhattan, NY</p>
        </div>
        <div class="pull-right col-xs-2">
          <strong>04/14 - Present</strong>
        </div>
      </div>
      <div class="col-xs-12">
        <ul>
          <li>Unilever, Corporate Interior, Multi-storey high-end experiential interior design project for a world renowned Consumer Product Company in Tribeca, Manhattan (20,000 SF): Project Manager and Designer. Lead the project from start to finish.</li>
          <li>NASDAQ, Corporate Interior, Two storey high-end corporate interior design project for a top Finance and Technology Company in Time Square, Manhattan (20,000 SF): Senior Designer. Designed the space to fit the needs of the client’s aesthetic, brand, schedule and budget.  </li>
        </ul>
      </div>
  -
    id: "resume_buck_moorhead_popup"
    copy: |
      <div class="col-xs-12">
        <div class="pull-left col-xs-10">
          <h1>Buck Moorhead Architect, Junior Architect</h1>
          <p>New York, NY</p>
        </div>
        <div class="pull-right col-xs-2">
          <strong>08/05 - 10/06</strong>
        </div>
      </div>
      <div class="col-xs-12">
        <ul>
          <li>Audubon Center for Sustainability, Interpretive Center, LEED certification aimed, Albany, NY, (3,000 sf):  LEED consultant, Schematic Design.</li>
          <li>Small Residential Lofts and apartment interior Renovation Projects, NYC, NY: Survey, DOB Filling, Construction Documents.</li>
        </ul>
      </div>
  -
    id: "resume_grad_assoc_popup"
    copy: |
      <div class="col-xs-12">
        <div class="pull-left col-xs-10">
          <h1>Grad Associates, P.A., Intermediate Architect</h1>
          <p>Newark, NJ</p>
        </div>
        <div class="pull-right col-xs-2">
          <strong>10/06 - 01/10</strong>
        </div>
      </div>
      <div class="col-xs-12">
        <ul>
          <li>Rensselaer Education Center, Green Building Award winning project, LEED Platinum aimed, 8.8-acre Ecological Park with a Center for Sustainability, Rensselaer, NY, (3,800 sf):  LEED Online, Redesign for value engineering, Project Management.</li>
          <li>Standard Chartered Bank, Cooperate Office Interiors, Newark, NJ (45,000 sf): Survey, Schematic Design, Product Research, Construction Documents.</li>
          <li>Starbucks Café, Café Interiors, Newark, NJ (500 SF): Survey, Project and Design coordination with company Standards and specifications, Site supervision.</li>
          <li>700 Broadway, Lobby Interior Design, New York, NY (600 sf): Schematic Design, Design Development.</li>
        </ul>
      </div>
  -
    id: "resume_diabes_popup"
    copy: |
      <div class="col-xs-12">
        <div class="pull-left col-xs-10">
          <h1>Daibes Design Group, Intermediate Architect</h1>
          <p>Edgewater, NJ</p>
        </div>
        <div class="pull-right col-xs-2">
          <strong>01/10 – 04/14</strong>
        </div>
      </div>
      <div class="col-xs-12">
        <ul>
          <li>The Alexander, Multi-storey Luxury Residential Apartment project in Edgewater, NJ (650,000 SF, 300 apartments): Construction Documents, Project Coordination and Construction Administration.</li>
          <li>Multiple small to midsized residential and commercial development projects in New Jersey.</li>
        </ul>
      </div>
