panel:
  width: 1920
  height: 1080
objects:
  -
    id: "container"
    location:
      top: 0
      left: 0
    dimensions:
      width: 1920
      height: 4860
  -
    id: "intro_hydrant"
    image_url: "/img/intro_hydrant.jpg"
    location:
      top: 41
      left: 309
    dimensions:
      width: 1301
      height: 756
    classes:
      - img-round-corners
  -
    id: "intro_shoes"
    image_url: "/img/intro_shoes.png"
    location:
      top: 0
      left: 1219
    dimensions:
      width: 377
      height: 583
  -
    id: "intro_signature"
    image_url: "/img/intro_signature.png"
    location:
      top: 0
      left: 36
    dimensions:
      width: 893
      height: 381
    parallax:
      parallax_id: intro_parallax
      scale: 0.04
  -
    id: "intro_tagline"
    image_url: "/img/intro_tagline.png"
    location:
      top: 460
      left: 1060
    dimensions:
      width: 592
      height: 368
    parallax:
      parallax_id: intro_parallax
      scale: 0.015
  -
    id: "great_button"
    location:
      top: 672
      left: 857
    button:
      text: "Great!"
    classes:
      - btn
      - btn-success
  -
    id: "portfolio_background"
    image_url: "/img/portfolio_background.jpg"
    location:
      top: 863
      left: 0
    dimensions:
      width: 1919
      height: 1024
    classes:
      - img-round-corners
  -
    id: "portfolio_title_parallax02"
    image_url: "/img/portfolio_title_parallax02.png"
    location:
      top: 859
      left: 154
    dimensions:
      width: 273
      height: 83
    parallax:
      parallax_id: portfolio_parallax
      scale: 0.05
  -
    id: "portfolio_title_parallax01"
    image_url: "/img/portfolio_title_parallax01.png"
    location:
      top: 848
      left: 159
    dimensions:
      width: 303
      height: 91
    parallax:
      parallax_id: portfolio_parallax
      scale: 0.025
  -
    id: "portfolio_title"
    image_url: "/img/portfolio_title.png"
    location:
      top: 846
      left: 161
    dimensions:
      width: 868
      height: 91
  -
    id: "portfolio_gallery_instagram_container"
    location:
      top: 914
      left: 0
    dimensions:
      width: 1919
      height: 915
    container:
      id: portfolio_gallery_instagram
      view_script: "partials/index/portfolio_gallery_instagram.twig.html"
    slides_gallery:
      id: portfolio_gallery_instagram
      trigger_id: portfolio_trigger_instagram
  -
    id: "portfolio_gallery_regular_container"
    location:
      top: 914
      left: 0
    dimensions:
      width: 1919
      height: 915
    container:
      id: portfolio_gallery_regular
      view_script: "partials/index/portfolio_gallery_regular.twig.html"
    slides_gallery:
      id: portfolio_gallery_regular
      trigger_id: portfolio_trigger_gallery
  -
    id: "portfolio_trigger_gallery_swap"
    image_url: "/img/portfolio_trigger_gallery_hover.png"
    location:
      top: 875
      left: 865
    dimensions:
      width: 116
      height: 39
    hidden: true
  -
    id: "portfolio_trigger_instagram_swap"
    image_url: "/img/portfolio_trigger_instagram_hover.png"
    location:
      top: 875
      left: 692
    dimensions:
      width: 140
      height: 39
    hidden: true
  -
    id: "portfolio_trigger_gallery"
    image_url: "/img/portfolio_trigger_gallery.png"
    alt: "Regular Gallery"
    location:
      top: 875
      left: 865
    dimensions:
      width: 116
      height: 39
    hover_swap:
      swap_image_src: "/img/portfolio_trigger_gallery_hover.png"
    slides_gallery_trigger:
      swap_image_src: "/img/portfolio_trigger_gallery_hover.png"
    click_scroll:
      scroll_y: 825
      duration: 1
  -
    id: "portfolio_trigger_instagram"
    image_url: "/img/portfolio_trigger_instagram.png"
    alt: "Instagram Gallery"
    location:
      top: 875
      left: 692
    dimensions:
      width: 140
      height: 39
    hover_swap:
      swap_image_src: "/img/portfolio_trigger_instagram_hover.png"
    slides_gallery_trigger:
      swap_image_src: "/img/portfolio_trigger_instagram_hover.png"
    click_scroll:
      scroll_y: 825
      duration: 1
  -
    id: "whatido_background"
    image_url: "/img/whatido_background.jpg"
    location:
      top: 2016
      left: 203
    dimensions:
      width: 1514
      height: 862
    classes:
      - img-round-corners
  -
    id: "whatido_title"
    image_url: "/img/whatido_title.png"
    location:
      top: 1936
      left: 163
    dimensions:
      width: 438
      height: 113
  -
    id: "whatido_copy"
    container:
      id: whatido_copy_markup
      view_script: "partials/index/whatido_copy.twig.html"
    location:
      top: 2016
      left: 203
    dimensions:
      width: 1514
      height: 862
parallax:
  -
    id: intro_parallax
    location:
      left: 857
      top: 672
  -
    id: portfolio_parallax
    location:
      left: 165
      top: 849
